Repository hmcts/div-case-maintenance-service, pull requests merged in 2019-01, with the labels that each got.

#60 update mutation tests
  build.gradle
Labels: ns:div-cms-pr-60

#59 DIV-3830: Replaced invalid emails with proper gov-notify one
  src/integrationTest/resources/ccd-submission-payload/addresses-no-hwf.json
  src/integrationTest/resources/ccd-submission-payload/addresses.json
  src/integrationTest/resources/ccd-submission-payload/d8-document.json
  src/integrationTest/resources/ccd-submission-payload/how-name-changed.json
  src/integrationTest/resources/ccd-submission-payload/jurisdiction-6-12.json
  src/integrationTest/resources/ccd-submission-payload/jurisdiction-all.json
  src/integrationTest/resources/ccd-submission-payload/linked-case.json
  src/integrationTest/resources/ccd-submission-payload/reason-adultery.json
  src/integrationTest/resources/ccd-submission-payload/reason-desertion.json
  src/integrationTest/resources/ccd-submission-payload/reason-separation.json
  src/integrationTest/resources/ccd-submission-payload/reason-unreasonable-behaviour.json
  src/integrationTest/resources/ccd-submission-payload/same-sex.json
  src/integrationTest/resources/ccd-update-payload/update-addresses.json
  src/test/resources/ccd-submission-payload/addresses-no-hwf.json
  src/test/resources/ccd-submission-payload/addresses.json
Labels: ns:div-cms-pr-59

#54 Retrieve Petition by CaseId for Citizen
  src/integrationTest/java/uk/gov/hmcts/reform/divorce/petition/CcdRetrieveCaseByIdTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/divorce/support/PetitionSupport.java
  src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/controller/PetitionController.java
  src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/CcdRetrievalService.java
  src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/PetitionService.java
  src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/CcdRetrievalServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/PetitionServiceImpl.java
  src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/controller/PetitionControllerUTest.java
  src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/RetrievePetitionByCaseIdITest.java
  src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/CcdRetrievalServiceImplUTest.java
  src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/PetitionServiceImplUTest.java
Labels: ns:div-cms-pr-54

#63 Remove unused imports and fix Wiremock Content Cleanup on Functional Unit tests
  src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/CcdSubmissionITest.java
  src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/CcdUpdateITest.java
  src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/CreateDraftServiceITest.java
  src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/DeleteDraftServiceITest.java
  src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/GetCaseITest.java
  src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/LinkRespondentITest.java
  src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/RetrieveAOSPostCompletedITest.java
  src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/RetrieveAllDraftsServiceITest.java
  src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/RetrieveAosCaseITest.java
  src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/RetrievePetitionByCaseIdITest.java
  src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/RetrievePetitionITest.java
  src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/SaveDraftServiceITest.java
  src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/UnlinkUserITest.java
Labels: ns:div-cms-pr-63

#68 DIV-3885 added health check timeout
  src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/config/HttpConnectionConfiguration.java
  src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/management/monitoring/health/CaseFormatterServiceHealthCheck.java
  src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/management/monitoring/health/DraftStoreHealthCheck.java
  src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/management/monitoring/health/IdamApiHealthCheck.java
  src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/management/monitoring/health/ServiceAuthProviderHealthCheck.java
  src/main/resources/application.yml
  src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/management/monitoring/health/HealthCheckITest.java
Labels: ns:div-cms-pr-68

#69 Revert to normal ASP
  infrastructure/main.tf
Labels: ns:div-cms-pr-69

#71 DIV-3814 - removed dependency check suppression for CVE-2018-8088
  dependency-check-suppressions.xml
Labels: ns:div-cms-pr-71

#75 Force jackson-databind version 2.9.8
  build.gradle
Labels: ns:div-cms-pr-75
