Repository hmcts/div-case-maintenance-service, pull requests merged in 2020-02, with the labels that each got.

#257 HOTFIX - Bump up Netty version to resolve CVE-2019-20445
  build.gradle
Labels: ns:divorce, rel:div-cms-pr-257

#260 RPET-58: Remove the deprecated enableDockerBuild() configuration
  Jenkinsfile_CNP
Labels: ns:divorce, rel:div-cms-pr-260

#262 fix OWASP dependency check
  build.gradle
  checkstyle.xml
  src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/controller/PetitionController.java
  src/main/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/service/impl/PetitionServiceImpl.java
  src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/functionaltest/RetrievePetitionByCaseIdITest.java
Labels: ns:divorce, rel:div-cms-pr-262

#269 fix OWASP dependency check
  build.gradle
Labels: ns:divorce, rel:div-cms-pr-269
