Repository hmcts/div-case-maintenance-service, pull requests merged in 2020-01, with the labels that each got.

#240 fix zap python compatibility issue
  build.gradle
  security.sh
Labels: ns:div-cms-pr-240, ns:divorce, rel:div-cms-pr-240

#253 Address CVE-2020-5398
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:divorce, rel:div-cms-pr-253

#254 FIX-Update spring version and modify health check tests
  build.gradle
  dependency-check-suppressions.xml
  src/test/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/management/monitoring/health/HealthCheckITest.java
Labels: ns:divorce, rel:div-cms-pr-254
