Repository hmcts/div-case-maintenance-service, pull requests merged in 2020-10, with the labels that each got.

#355 upgrade AzureRM to 2.x to match shared infra
  dependency-check-suppressions.xml
  infrastructure/.terraform-version
  infrastructure/main.tf
  infrastructure/output.tf
  infrastructure/state.tf
  infrastructure/variables.tf
Labels: ns:divorce, prd:div, rel:div-cms-pr-355

#357 RPET-520: bump owasp
  build.gradle
Labels: ns:divorce, prd:div, rel:div-cms-pr-357

#361 Ta 29 data store consumer test
  Jenkinsfile_CNP
  build.gradle
  src/contractTest/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/client/DraftStoreClientConsumerTest.java
  src/contractTest/resources/application.yml
  src/contractTest/resources/json/base-case.json
Labels: ns:divorce, prd:div, rel:div-cms-pr-361

#362 Run functional tests in nightly build
  Jenkinsfile_nightly
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:divorce, prd:div, rel:div-cms-pr-362

#364 TA-28: Fix publish pact verification
  build.gradle
Labels: ns:divorce, prd:div, rel:div-cms-pr-364
